version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "paintez-appointment-system"
s3_prefix = "paintez-appointment-system"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
